name: Despliegue a AWS Produccion

on:
  push:
    branches:
      - main 

jobs:
  desplegar:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4 
      - name: Conectarse a AWS y Desplegar
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }} 
          username: ${{ secrets.SERVER_USER }} 
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          
          script: |
            cd ~/mi-proyecto # <- OJO AQUI
            git pull origin main
            docker compose down
            docker compose up -d --build